// frontend/src/components/StatsCounter.tsx
import React from 'react'

export default function StatsCounter({ icon, label, value }: { icon: string; label: string; value: number }) {
  return (
    <div className="stats-counter relative overflow-hidden rounded-lg border bg-card p-4 text-card-foreground shadow-sm transition-all duration-300">
      <div className="flex flex-col items-center space-y-2">
        <div className="text-3xl" aria-hidden>
          {icon}
        </div>
        <div className="counter-value relative h-12 w-full overflow-hidden text-center">
          <span className="text-4xl font-bold tabular-nums">{value}</span>
        </div>
        <div className="text-sm font-medium text-muted-foreground">{label}</div>
      </div>
    </div>
  )
}

// frontend/src/lib/components/StatsCounter.svelte
<!-- StatsCounter.svelte -->
<script lang="ts">
  // Props
  export let icon: string;
  export let label: string;
  export let value: number = 0;
</script>

<div class="stats-counter relative overflow-hidden rounded-lg border bg-card p-4 text-card-foreground shadow-sm transition-all duration-300">
  <div class="flex flex-col items-center space-y-2">
    <!-- Icon -->
    <div class="text-3xl" aria-hidden="true">
      {icon}
    </div>
    
    <!-- Counter value -->
    <div class="counter-value relative h-12 w-full overflow-hidden text-center">
      <span class="text-4xl font-bold tabular-nums">
        {value}
      </span>
    </div>
    
    <!-- Label -->
    <div class="text-sm font-medium text-muted-foreground">
      {label}
    </div>
  </div>
</div>

<style>
  .counter-value {
    transition: color 0.3s ease;
  }
</style>
